---
log: ~
mailfetch_opts:
  expunge_immediately: 1
  mark_delete_on_success: 0
  mark_seen_on_error: 1
  mark_seen_on_success: 1
  search_flag: UNSEEN
  time_range_max_in_day: 1
  time_range_min_in_day: ~
output_dir:
  data:
    - dev/data
    - template: :YEAR
    - template: :MONTH
    - template: :DATE
    - template: :MAILBOX
    - template: :TIMESTAMP--:UID
  meta:
    - dev/meta
    - template: :YEAR
    - template: :MONTH
    - template: :DATE
    - template: :MAILBOX
    - template: :TIMESTAMP--:UID
  tasklog:
    - dev/task  
target_mailboxes:
  - account: stephenwan@udomain.com.hk
    password:
      file: .secret
    server: mail102@udomain.com.hk
    folders:
      - INBOX
      - SPAM
t:
  ConfigProvider:
    readscalar: "README"
    readarray:
      - zero
      - one
        
